### ISSUE TITLE
'account.invoice' object has no attribute 'payment_mode_id'

### ISSUE THREAD

**Issue by lorenzyannick** [OCA/l10n-france#203]
Hi,

I try a fresh odoo 10 install (on debian 8)
with l10n-france and chorus account (branch 10)

When I try to validate an invoice I get this error : 

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 899, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 887, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/account/models/account_invoice.py", line 587, in action_invoice_open
    to_open_invoices.action_move_create()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/l10n_fr_chorus_account/models/account_invoice.py", line 89, in action_move_create
    if not self.payment_mode_id:
AttributeError: 'account.invoice' object has no attribute 'payment_mode_id'
```

I don't find any clue how to solve this.
Maybe I have a plugin missing ? so there is a dependency error ?
Thank you

**Comment by lorenzyannick** [comment]
I solved this adding 
account_payment_partner
account_payment_mode
account_payment_sale
account_payment_order
account_banking_pain_base
account_banking_mandate

**Comment by abdallah-hellmy** [comment]
i write the same dependency but its raise another error on another field in the same module
