### ISSUE TITLE
Import French CFONB Bank Statements V14

### ISSUE THREAD

**Issue by Naturamat** [OCA/l10n-france#293]
After installation of Import French CFONB Bank Statements, when importing a file whe have error
Any idea what's happening ?
Erreur:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/enterprise/account_bank_statement_import/account_bank_statement_import.py", line 53, in import_file
    statement_ids, statement_line_ids, notifications = self._create_bank_statements(stmts_vals)
  File "/home/odoo/src/enterprise/account_bank_statement_import/account_bank_statement_import.py", line 270, in _create_bank_statements
    statement = BankStatement.create(st_vals)
  File "<decorator-gen-186>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 344, in _model_create_multi
    return create(self, [arg])
  File "/home/odoo/src/odoo/addons/account/models/account_bank_statement.py", line 275, in create
    res = super(AccountBankStatement, self).create(values)
  File "<decorator-gen-133>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/addons/mail/models/mail_thread.py", line 264, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-65>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_fields.py", line 533, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/odoo/models.py", line 3868, in create
    records = self._create(data_list)
  File "/home/odoo/src/odoo/odoo/models.py", line 4026, in _create
    field.create([
  File "/home/odoo/src/odoo/odoo/fields.py", line 3041, in create
    self.write_batch(record_values, True)
  File "/home/odoo/src/odoo/odoo/fields.py", line 3067, in write_batch
    return self.write_real(records_commands_list, create)
  File "/home/odoo/src/odoo/odoo/fields.py", line 3239, in write_real
    flush()
  File "/home/odoo/src/odoo/odoo/fields.py", line 3203, in flush
    comodel.create(to_create)
  File "<decorator-gen-187>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/addons/account/models/account_bank_statement.py", line 858, in create
    st_lines = super().create(vals_list)
  File "<decorator-gen-65>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_fields.py", line 533, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/odoo/models.py", line 3825, in create
    raise ValueError("Invalid field %r on model %r" % (key, self._name))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Invalid field 'note' on model 'account.bank.statement.line'

**Comment by alexis-via** [comment]
The problem is on your side.
The backtrace don't show the OCA module account_statement_import_fr_cfonb
The backtrace mention the enterprise account_bank_statement_import and not the OCA module account_statement_import from https://github.com/OCA/bank-statement-import
